### ISSUE TITLE
attempt to concatenate field 'address' (a nil value) when using CNAME'd domain

### ISSUE THREAD

**Issue by jordanade** [jkeys089/lua-resty-resolver#5] opened 2019-01-25 13:06 UTC
I'm basically copying most of what I found in the synopsis and got this error.
```
[error] 21#21: *6 lua entry thread aborted: runtime error: /usr/local/openresty/site/lualib/resolver/master.lua:172: attempt to concatenate field 'address' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/openresty/site/lualib/resolver/master.lua: in function 'set'
	/usr/local/openresty/site/lualib/resolver/master.lua:70: in function 'resolve'
	/usr/local/openresty/site/lualib/resolver/master.lua:132: in function </usr/local/openresty/site/lualib/resolver/master.lua:130>, context: ngx.timer
```
Any ideas?

**Comment by jkeys089** [comment] 2019-01-25 21:52
@jordanade could you provide the minimal code which reproduces this error?

**Comment by jordanade** [comment] 2019-01-26 04:53
```
user nginx;
daemon off;
error_log /logs/error.log info;
worker_processes 5;

events {
}

http {
  lua_package_path "/usr/local/openresty/site/lualib/resolver/?.lua;;";
  lua_shared_dict dns_cache 1m;

  init_by_lua_block {
    local err
    jottful_master, err = require("resolver.master"):new("dns_cache", "server.jottful.com", {"1.1.1.1"})
    if not jottful_master then
      error("Failed to create server.jottful.com resolver master: " .. err)
    end
  }

  init_worker_by_lua_block {
    jottful_master:init()
    local err
    jottful_client, err = jottful_master:client()
    if not jottful_client then
      error("Failed to create server.jottful.com resolver client: " .. err)
    end
  }
}
```

I can also provide the Dockerfile if you like.

**Comment by jordanade** [comment] 2019-01-26 08:56
Figured it out. It seems to be due to the fact that I'm using a CNAME to point the domain server.jottful.com to the actual domain of the server.

**Comment by vashibhavin** [comment] 2020-05-08 06:56
I just hit this issue. How does one work CNAME's in that case?

**Comment by jkeys089** [comment] 2020-05-08 21:27
@vashibhavin internally we're using https://github.com/openresty/lua-resty-dns to resolve DNS queries. At the moment, only A records are supported (see: https://github.com/jkeys089/lua-resty-resolver/blob/master/lib/resolver/master.lua#L122). If we wanted to add support for CNAME records I suppose we'd need to attempt a CNAME query and recursively resolve that result until we reach an A record (or AAAA if we wanted to support IPv6 as well). It would be great to support CNAME's and AAAA records but it would take a bit of work to add.

**Comment by vashibhavin** [comment] 2020-05-12 04:56
@jkeys089 Thanks for your prompt response. Yeah, I did see why this does not work with CNAME's. But just wasn't expecting CNAME's to not work. But your perspective definitely helps here. 

Would it make sense to re-open this issue so that people interested in using this library are aware of the lack of support for AAAA and CNAME's?

**Comment by vashibhavin** [comment] 2020-05-12 09:03
So I was digging some more and I realized that if we set `qopts` to nil https://github.com/jkeys089/lua-resty-resolver/blob/master/lib/resolver/master.lua#L122, the query method returns back all the answer records.

e.g.
```
$ dig +noall +answer www.microsoft.com
www.microsoft.com.	96	IN	CNAME	www.microsoft.com-c-3.edgekey.net.
www.microsoft.com-c-3.edgekey.net. 14074 IN CNAME www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net.
www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net. 510 IN CNAME e13678.dspb.akamaiedge.net.
e13678.dspb.akamaiedge.net. 6	IN	A	72.247.102.30
```

I am new to LUA so still trying to figure out the ecosystem, but I managed to put together a test of sorts which shows the response from the query method

```
# vim:set ft= ts=4 sw=4 et:

use Test::Nginx::Socket::Lua;
use Cwd qw(cwd);

# repeat_each(2);

plan tests => repeat_each() * (2 * blocks());

my $pwd = cwd();

$ENV{TEST_NGINX_RESOLVER} ||= '8.8.8.8';

our $HttpConfig = qq(
    lua_package_path "$pwd/t/lib/?.lua;$pwd/lib/?.lua;;";
    lua_package_cpath "/usr/local/openresty-debug/lualib/?.so;/usr/local/openresty/lualib/?.so;;";
    resolver '$ENV{TEST_NGINX_RESOLVER}';
);

# no_long_string();

run_tests();

__DATA__

=== TEST 1: CNAME records
--- http_config eval: $::HttpConfig
--- config
    location /t {
        content_by_lua '
            local resolver = require "resty.dns.resolver"

            local r, err = resolver:new{ nameservers = { "$TEST_NGINX_RESOLVER" } }
            if not r then
                ngx.say("failed to instantiate resolver: ", err)
                return
            end

            local ans, err = r:query("www.microsoft.com")
            if not ans then
                ngx.say("failed to query: ", err)
                return
            end

            local ljson = require "ljson"
            ngx.say("records: ", ljson.encode(ans))
        ';
    }
--- request
GET /t
--- response_body_like chop
^records
```
And here are the results.
```
$ ./test.sh -v t/cname.t
t/cname.t ..
1..2
ok 1 - TEST 1: CNAME records - status code ok
ok 2 - TEST 1: CNAME records - response_body_like - response is expected (records: [{"class":1,"cname":"www.microsoft.com-c-3.edgekey.net","name":"www.microsoft.com","section":1,"ttl":494,"type":5},{"class":1,"cname":"www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net","name":"www.microsoft.com-c-3.edgekey.net","section":1,"ttl":19426,"type":5},{"class":1,"cname":"e13678.dspb.akamaiedge.net","name":"www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net","section":1,"ttl":698,"type":5},{"address":"23.204.251.223","class":1,"name":"e13678.dspb.akamaiedge.net","section":1,"ttl":19,"type":1}])
ok
All tests successful.
Files=1, Tests=2,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.11 cusr  0.06 csys =  0.18 CPU)
Result: PASS
```
As you can see, the `query()` method seems to be returning back 4 records including 3 CNAMEs and 1 A record. If that is the case, then it looks like the recursive resolution is taken care of by the lua-resty-dns library or maybe in one of its dependencies. 

Do you think it would be safe to just do something like below over here https://github.com/jkeys089/lua-resty-resolver/blob/master/lib/resolver/master.lua#L187

```
            -- Only insert the address records and skip everything else
            if ans.address then
                cache:set(prefix .. ans.address, exp, ttl)
            end
```

**Comment by jkeys089** [comment] 2020-05-12 11:06
@vashibhavin thanks for the detailed response. If you'd like to open another feature request issue for CNAME support I'd be OK leaving that one open in case someone wants to contribute in the future.

With regard to omitting the `qtype`, I don't think it would actually help in the case of a CNAME. Only A records and AAAA records will return an `address` and I think we'd want to make IPv6 an opt-in rather than the default (at least for now). If we really want to support CNAME's we'd need to support recursive resolution until we get to an IP address.

**Comment by vashibhavin** [comment] 2020-05-13 05:49
Thanks for your response. I am a little confused about the recursive resolution piece. I ran the test [mentioned above](https://github.com/jkeys089/lua-resty-resolver/issues/5#issuecomment-627212117)  and started a `tcpdump` run to see the traffic.

```
$ sudo tcpdump -i en0 port 53
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on en0, link-type EN10MB (Ethernet), capture size 262144 bytes

10:50:23.438112 IP 192.168.2.129.59798 > dns.google.domain: 45799+ A? www.microsoft.com. (35)
10:50:23.497137 IP dns.google.domain > 192.168.2.129.59798: 45799 4/0/0 CNAME www.microsoft.com-c-3.edgekey.net., CNAME www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net., CNAME e13678.dspb.akamaiedge.net., A 103.95.85.21 (202)
10:50:23.550581 IP 192.168.2.129.51378 > dns.google.domain: 49363+ A? www.microsoft.com. (35)
10:50:23.576379 IP dns.google.domain > 192.168.2.129.51378: 49363 4/0/0 CNAME www.microsoft.com-c-3.edgekey.net., CNAME www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net., CNAME e13678.dspb.akamaiedge.net., A 103.95.85.21 (202)
^C
4 packets captured
78 packets received by filter
0 packets dropped by kernel
```
I ran the above configuration and tried to dump the response from the [call to `query()`](https://github.com/jkeys089/lua-resty-resolver/blob/master/lib/resolver/master.lua#L43)

```
2020/05/13 05:40:14 [error] 4666#4666: *18 [lua] master.lua:97: resolve(): { [1] = { ["cname"] = www.microsoft.com-c-3.edgekey.net,["class"] = 1,["ttl"] = 42,["name"] = www.microsoft.com,["section"] = 1,["type"] = 5,} ,[2] = { ["cname"] = www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net,["class"] = 1,["ttl"] = 42,["name"] = www.microsoft.com-c-3.edgekey.net,["section"] = 1,["type"] = 5,} ,[3] = { ["cname"] = e13678.dspb.akamaiedge.net,["class"] = 1,["ttl"] = 42,["name"] = www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net,["section"] = 1,["type"] = 5,} ,[4] = { ["address"] = 173.222.229.190,["class"] = 1,["ttl"] = 20,["name"] = e13678.dspb.akamaiedge.net,["section"] = 1,["type"] = 1,} ,} , context: ngx.timer
```
The lua-resty-dns library seems to be receiving the recursively resolved A record from the DNS server and it looks like it passes all of that information as the return value of the `query()` method. 

Maybe it is my lack of understanding of how DNS works, but I am not sure why we would have to do the recursive resolution at all in the library.

**Comment by jkeys089** [comment] 2020-05-13 19:24
@vashibhavin Perhaps I'm confused about your request for CNAME support specifically. Are you encountering an actual error or was this just a general question? I think there may be some confusion about how [lua-resty-dns](https://github.com/openresty/lua-resty-dns) is working under the hood. When you request a CNAME record, it will not recursively resolve to an IP address. When you omit a record type it actually defaults to `TYPE_A` (same as this library). However, this doesn't mean this lib automatically breaks if you use a sub-domain that utilizes a CNAME, it just means that you delegate control over the resolution to your DNS server. In many cases this just works as expected but in some environments it will not work (e.g. your DNS server doesn't support recursion for security reasons).

To put it in terms of another tool:
```
# request CNAME record
$> dig +noall +short -t CNAME www.microsoft.com @8.8.8.8
www.microsoft.com-c-3.edgekey.net.

# request CNAME record with a non-recursive query
$> dig +noall +short +norecurse -t CNAME www.microsoft.com @8.8.8.8
www.microsoft.com-c-3.edgekey.net.
# same result as recursive query above!

# request A record
$> dig +noall +short -t A www.microsoft.com @8.8.8.8
www.microsoft.com-c-3.edgekey.net.
www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net.
e13678.dspb.akamaiedge.net.
184.26.82.115

# request A record with a non-recursive query
$> dig +noall +short +norecurse -t A www.microsoft.com @8.8.8.8
# no results :-(

# request AAAA record
$> dig +noall +short -t AAAA www.microsoft.com @8.8.8.8
www.microsoft.com-c-3.edgekey.net.
www.microsoft.com-c-3.edgekey.net.globalredir.akadns.net.
e13678.dspb.akamaiedge.net.
2600:1409:d000:38a::356e
2600:1409:d000:3a7::356e

# request AAAA record with a non-recursive query
$> dig +noall +short +norecurse -t AAAA www.microsoft.com @8.8.8.8
# no results :-(
```

If your DNS server supports recursive queries then you should have no issue using this library as-is. If you cannot use a DNS server that supports recursive queries, you must recursively resolve the CNAME yourself. Hopefully that makes sense.

**Comment by jkeys089** [comment] 2020-05-13 20:02
@vashibhavin I just wrote a quick test to try and help explain and realized the issue. I mistakenly thought you wanted top-level support for CNAME records but now I realize now this lib is just horribly broken when processing _any_ answers that contain CNAME resource records 🤦. Sorry for the miscommunication!

@jordanade apologies for closing this issue without fully understanding the problem.

**Closed** 2020-05-13 20:04 UTC
